name: Sitemap-Generator

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
  workflow_dispatch : 


jobs:
  sitemap-generator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          ref: sitemap
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        run: |
            npm install
            node index.js
            ls -la
            curl -i -X PUT -H 'Authorization: token ${{ github.token }}' -d "{\"path\": \"sitemap.xml\", \"message\": \"update\", \"content\": \"$(openssl base64 -A -in sitemap.xml)\", \"branch\": \"gh-pages\",\"sha\": $(curl -X GET https://api.github.com/repos/etrolls/troll-bank/contents/sitemap.xml?ref=gh-pages | jq .sha)}" https://api.github.com/repos/etrolls/troll-bank/contents/sitemap.xml?ref=gh-pages
        
